"""Add GroupMembership model

Revision ID: 0b0fcc6bf83d
Revises: 793ad89b3a3c
Create Date: 2025-06-20 01:13:14.968290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0b0fcc6bf83d'
down_revision = '793ad89b3a3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_memberships',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'student_id')
    )
    op.drop_table('group_membership')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index('ix_groups_teacher_id')
        batch_op.drop_constraint('groups_teacher_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['teacher_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('groups_teacher_id_fkey', 'teachers', ['teacher_id'], ['id'])
        batch_op.create_index('ix_groups_teacher_id', ['teacher_id'], unique=False)

    op.create_table('group_membership',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='group_membership_group_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='group_membership_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'group_id', name='group_membership_pkey')
    )
    op.drop_table('group_memberships')
    # ### end Alembic commands ###
