"""Add Teacher model

Revision ID: 2269a3557a1e
Revises: ff3274f62d60
Create Date: 2025-06-18 12:36:08.720791

"""
from alembic import op
import models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2269a3557a1e'
down_revision = 'ff3274f62d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_sessions', schema=None) as batch_op:
        batch_op.alter_column('total_questions',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('correct_answers',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('teacher_exercises', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_constraint('teachers_user_id_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_teachers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teachers_user_id'), ['user_id'], unique=True)
        batch_op.drop_constraint('teachers_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('teachers_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_teachers_user_id'))
        batch_op.drop_index(batch_op.f('ix_teachers_id'))
        batch_op.create_unique_constraint('teachers_user_id_key', ['user_id'])
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('teacher_exercises', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.JSON(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)

    with op.batch_alter_table('practice_sessions', schema=None) as batch_op:
        batch_op.alter_column('correct_answers',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_questions',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
