"""Add homework and group membership models

Revision ID: 793ad89b3a3c
Revises: ad544b25a83e
Create Date: 2025-06-19 14:02:50.976446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793ad89b3a3c'
down_revision = 'ad544b25a83e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_membership',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('homework',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['exercise_id'], ['teacher_exercises.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('homework', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_homework_assigned_by_id'), ['assigned_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_homework_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_homework_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_homework_id'), ['id'], unique=False)

    op.create_table('homework_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('homework_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['homework_id'], ['homework.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('homework_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_homework_submissions_homework_id'), ['homework_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_homework_submissions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_homework_submissions_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homework_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_homework_submissions_student_id'))
        batch_op.drop_index(batch_op.f('ix_homework_submissions_id'))
        batch_op.drop_index(batch_op.f('ix_homework_submissions_homework_id'))

    op.drop_table('homework_submissions')
    with op.batch_alter_table('homework', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_homework_id'))
        batch_op.drop_index(batch_op.f('ix_homework_group_id'))
        batch_op.drop_index(batch_op.f('ix_homework_exercise_id'))
        batch_op.drop_index(batch_op.f('ix_homework_assigned_by_id'))

    op.drop_table('homework')
    op.drop_table('group_membership')
    # ### end Alembic commands ###
