"""Refactor model relationships for Teacher and Exercise

Revision ID: ad544b25a83e
Revises: ddc958b652a8
Create Date: 2025-06-18 13:03:58.784462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad544b25a83e'
down_revision = 'ddc958b652a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_groups_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_teacher_id'), ['teacher_id'], unique=False)
        batch_op.drop_constraint('groups_teacher_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'teachers', ['teacher_id'], ['id'])

    with op.batch_alter_table('teacher_exercises', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_teacher_exercises_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_exercises_id'), ['id'], unique=False)
        batch_op.drop_constraint('teacher_exercises_creator_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'teachers', ['creator_id'], ['id'])

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_constraint('teachers_user_id_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_teachers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teachers_user_id'), ['user_id'], unique=True)
        batch_op.drop_constraint('teachers_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_botmaster', sa.Boolean(), nullable=False))
        batch_op.alter_column('stats',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('stats',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.drop_column('is_botmaster')

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('teachers_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_teachers_user_id'))
        batch_op.drop_index(batch_op.f('ix_teachers_id'))
        batch_op.create_unique_constraint('teachers_user_id_key', ['user_id'])
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('teacher_exercises', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('teacher_exercises_creator_id_fkey', 'users', ['creator_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_teacher_exercises_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_exercises_creator_id'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('groups_teacher_id_fkey', 'users', ['teacher_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_groups_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_groups_id'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###
